version: '3.1'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./SysRes
    container_name: SysRes
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SR
      - SPRING_DATASOURCE_USERNAME=SR
      - SPRING_DATASOURCE_PASSWORD=u!zEV2NY!k22tWk5
    networks:
      - networks_container
    ports:
      - 8080:8080
  db:
    image: 'postgres:latest'
    restart: always
    hostname: db
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=SR
      - POSTGRES_PASSWORD=u!zEV2NY!k22tWk5
      - POSTGRES_DB=SR
      - DATABASE_HOST= 127.0.0.1
    ports:
      - 5432:5432
    networks:
      - networks_container
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=josue.chaqui@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=u!zEV2NY!k22tWk5
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - networks_container
networks:
  networks_container:
    ipam:
      config:
        - subnet: 172.21.0.0/16
volumes:
    postgres_data:
        driver: local