version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: SysRes
    container_name: SysRes
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=SR
      - SPRING_DATASOURCE_PASSWORD=u!zEV2NY!k22tWk5
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    build:
      context: SysRes
    container_name: db
    environment:
      - POSTGRES_USER=SR
      - POSTGRES_PASSWORD=u!zEV2NY!k22tWk5