version: '3.1'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./SysRes
    container_name: SysRes
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SR
      - SPRING_DATASOURCE_USERNAME=SR
      - SPRING_DATASOURCE_PASSWORD=u!zEV2NY!k22tWk5
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - networks_container
    ports:
      - 8080:8080
  db:
    image: 'postgres:13.1-alpine'
    hostname: db
    build:
      context: ./db
    container_name: db
    volumes:
      - restauranteChaquiVol:/var/lib/postgresql
    environment:
      - POSTGRES_USER=SR
      - POSTGRES_PASSWORD=u!zEV2NY!k22tWk5
      - POSTGRES_DB=SR
    ports:
      - 5432:5432
    networks:
      - networks_container
networks:
  networks_container:
    ipam:
      config:
        - subnet: 172.21.0.0/16
volumes:
    restauranteChaquiVol:
        driver: local